spring:
  application:
    name: auth-service
    datasource:
      driver-class-name: org.postgresql.Driver
      username: ${SPACE_ROLE}
      password: ${SPACE_PASS}
      url: ${SPACE_URL}
    jpa:
      database: postgresql
      hibernate:
        ddl-auto: validate
        temp:
            use_jdbc_metadata_defaults: false
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles: dev

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

jwt:
  token:
    secret-key: SUPERDUPERSECRETKEY

server:
  port: 8255