spring:
  application:
    name: gateway-service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
server:
  port: 8662
zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  routes:
    auth-service:
     path: /users/**
     serviceId: auth-service
     stripPrefix: true
    nasa-service:
      path: /nasa/**
      serviceId: nasa-service
      stripPrefix: true