spring:
  application:
    name: nasa-service
#  cloud:
#    config:
#      uri: http://localhost:8888
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
server:
  port: 8888